name: umdapy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - numba
  - matplotlib
  - dask
  - dask-ml
  - tqdm
  - h5py
  - tabulate
  - loguru
  - pandas
  - flask
  - waitress
  - pip
  - pytables
  - selfies
  - pip:
    - astrochem-embedding
    - uncertainties
    - pyinstaller
    - flask-cors
    - git+https://github.com/guyrosin/mol2vec.git@gensim_v4

# conda env create -n umdapy -f src/conda.yml

# update if necessary after creating an environment
# conda activate umdapy
# conda env update -f src/conda.yml --prune
